FROM prom/prometheus:v2.53.0

COPY monitoring/prometheus/prometheus.yml /etc/prometheus/prometheus.yml
COPY monitoring/prometheus/alerting_rules.yml /etc/prometheus/alerting_rules.yml

USER root
RUN mkdir -p /prometheus && chown -R nobody:nogroup /prometheus
USER nobody

EXPOSE 9090
